In [19]:
import pandas as pd
klines = pd.read_csv('resource/dataset/binance/klines-BTCUSDT-1m_0413.csv')
# study = pd.read_csv('resource/dataset/StudentsStudyHour/Student Study Hour V3.csv')
del klines['openTime']
del klines['closeTime']
del klines['ignore']
# y_arr = klines['40688.10000000']
# del klines['1649693640000']
# x_arr = klines['40688.10000000']
klines.head()
y_arr = klines['close']
#
# x_study = study[['Hours']]
# y_study = study[['Scores']]
# # print(x_study.shape, y_study.shape)
# # print(x_study.head(2))
# # print(y_study.head(2))
#
# x_study['Hours'][0]
# y_study

In [27]:
del klines['close']
x_arr = klines

In [29]:
x_train = x_arr
y_train = y_arr

In [36]:
x_train

open      high       low     volume  quoteAssetVolume  \
0    40244.02  40244.02  40211.82   17.58826      7.074232e+05   
1    40212.25  40222.35  40205.06   15.84081      6.370153e+05   
2    40222.35  40225.44  40222.34   14.73552      5.927238e+05   
3    40225.44  40245.00  40225.43   12.10230      4.869392e+05   
4    40244.99  40245.00  40216.74   34.00800      1.368198e+06   
..        ...       ...       ...        ...               ...   
995  39907.32  39978.62  39905.40   64.53067      2.577749e+06   
996  39975.71  40057.07  39930.00   90.69511      3.628680e+06   
997  40056.80  40133.26  40031.11  125.34187      5.024398e+06   
998  40090.00  40142.91  40073.80   55.39164      2.221413e+06   
999  40135.38  40135.38  40118.56    1.69844      6.815997e+04   

     numberOfTrades  takerBuyBaseAssetVolume  takerBuyQuoteAssetVolume  
0               679                  8.65981              3.482811e+05  
1               662                 10.09546              4.059783e+05  
2               517                  9.29628              3.739357e+05  
3               507                  8.16210              3.284103e+05  
4               718                 10.71292              4.309755e+05  
..              ...                      ...                       ...  
995            1396                 33.45722              1.336247e+06  
996            1974                 60.58521              2.423641e+06  
997            2971                 85.91495              3.443750e+06  
998            1441                 33.79804              1.355253e+06  
999              78                  0.60550              2.430104e+04  

[1000 rows x 8 columns]

In [32]:
import tensorflow as tf
import numpy as np
# x_train = [1, 2, 3]
# y_train = [1, 2, 3]


W = tf.Variable(1, name="weight")
b = tf.Variable(1, name="bias")

testM = tf.keras.models.Sequential()
testM.add(tf.keras.layers.Dense(1, input_dim = 8,activation='linear'))

# hypothesis = (x_train['open']*W)+ + +b
# cost = tf.reduce_mean(tf.square(hypothesis - y_train['Scores']))

sgd = tf.keras.optimizers.SGD(learning_rate=0.01)
testM.compile(loss='mse',optimizer=sgd,metrics=['accuracy'])

history = testM.fit(x_train,y_train,epochs=15000,verbose=0,batch_size=1, shuffle=False)

# print(model.predict(np.array([5])))

In [51]:
testM.summary()
testM.get_weights()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 9         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


[array([[nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan]], dtype=float32),
 array([nan], dtype=float32)]

In [46]:
x_train['quoteAssetVolume'] = x_train['quoteAssetVolume'].astype(float)

In [48]:
x_train['takerBuyQuoteAssetVolume'] = x_train['takerBuyQuoteAssetVolume'].astype(float)

In [78]:
at = x_train.corr()
at

open      high       low    volume  \
open                      1.000000  0.995973  0.996398  0.203774   
high                      0.995973  1.000000  0.994737  0.250855   
low                       0.996398  0.994737  1.000000  0.169816   
volume                    0.203774  0.250855  0.169816  1.000000   
quoteAssetVolume          0.210047  0.257184  0.176277  0.999941   
numberOfTrades            0.193813  0.241764  0.158344  0.944773   
takerBuyBaseAssetVolume   0.194623  0.251879  0.173745  0.951989   
takerBuyQuoteAssetVolume  0.200203  0.257423  0.179435  0.952011   

                          quoteAssetVolume  numberOfTrades  \
open                              0.210047        0.193813   
high                              0.257184        0.241764   
low                               0.176277        0.158344   
volume                            0.999941        0.944773   
quoteAssetVolume                  1.000000        0.944668   
numberOfTrades                    0.944668        1.000000   
takerBuyBaseAssetVolume           0.952741        0.915966   
takerBuyQuoteAssetVolume          0.952863        0.915776   

                          takerBuyBaseAssetVolume  takerBuyQuoteAssetVolume  
open                                     0.194623                  0.200203  
high                                     0.251879                  0.257423  
low                                      0.173745                  0.179435  
volume                                   0.951989                  0.952011  
quoteAssetVolume                         0.952741                  0.952863  
numberOfTrades                           0.915966                  0.915776  
takerBuyBaseAssetVolume                  1.000000                  0.999952  
takerBuyQuoteAssetVolume                 0.999952                  1.000000

In [68]:
y_train['close']

KeyError: 'close'

In [76]:


# W = tf.Variable(1, name="weight")
# b = tf.Variable(1, name="bias")


W_1 = tf.Variable(1, name="weight_1")
W_2 = tf.Variable(1, name="weight_2")
W_3 = tf.Variable(1, name="weight_3")
W_4 = tf.Variable(1, name="weight_4")
W_5 = tf.Variable(1, name="weight_5")
W_6 = tf.Variable(1, name="weight_6")
W_7 = tf.Variable(1, name="weight_7")
W_8 = tf.Variable(1, name="weight_8")
b = tf.Variable(1, name="bias")


testM2 = tf.keras.models.Sequential()
testM2.add(tf.keras.layers.Dense(1, input_dim = 8,activation='linear'))

hypothesis = (x_train['open']*W_1)+(x_train['high']*W_2)+(x_train['low']*W_3)+(x_train['volume']*W_4)+(x_train['quoteAssetVolume']*W_5)+(x_train['numberOfTrades']*W_6)+(x_train['takerBuyBaseAssetVolume']*W_7)+(x_train['takerBuyQuoteAssetVolume']*W_8) + b

cost = tf.reduce_mean(tf.square(hypothesis - y_train))

sgd = tf.keras.optimizers.SGD(learning_rate=0.0000000001)
testM2.compile(loss='mse',optimizer=sgd,metrics=['accuracy'])

history2 = testM2.fit(x_train,y_train,epochs=30,verbose=2,batch_size=1, shuffle=False)


Epoch 1/30
1000/1000 - 1s - loss: nan - accuracy: 0.0000e+00 - 621ms/epoch - 621us/step
Epoch 2/30
1000/1000 - 0s - loss: nan - accuracy: 0.0000e+00 - 428ms/epoch - 428us/step
Epoch 3/30
1000/1000 - 0s - loss: nan - accuracy: 0.0000e+00 - 416ms/epoch - 416us/step
Epoch 4/30
1000/1000 - 0s - loss: nan - accuracy: 0.0000e+00 - 430ms/epoch - 430us/step
Epoch 5/30
1000/1000 - 0s - loss: nan - accuracy: 0.0000e+00 - 404ms/epoch - 404us/step
Epoch 6/30
1000/1000 - 0s - loss: nan - accuracy: 0.0000e+00 - 412ms/epoch - 412us/step
Epoch 7/30
1000/1000 - 0s - loss: nan - accuracy: 0.0000e+00 - 434ms/epoch - 434us/step
Epoch 8/30
1000/1000 - 0s - loss: nan - accuracy: 0.0000e+00 - 417ms/epoch - 417us/step
Epoch 9/30
1000/1000 - 0s - loss: nan - accuracy: 0.0000e+00 - 427ms/epoch - 427us/step
Epoch 10/30
1000/1000 - 0s - loss: nan - accuracy: 0.0000e+00 - 432ms/epoch - 432us/step
Epoch 11/30
1000/1000 - 0s - loss: nan - accuracy: 0.0000e+00 - 415ms/epoch - 415us/step
Epoch 12/30
1000/1000 - 0s - l

In [38]:
testM.predict([[40244.02,40244.02,40211.82,17.58826,707423.2,679, 8.65981,348281.1]])

array([[nan]], dtype=float32)

In [73]:
history.history

{'loss': [140.22091674804688,
  34.19613265991211,
  34.17905807495117,
  34.16621780395508,
  34.156578063964844,
  34.149375915527344,
  34.144004821777344,
  34.14004135131836,
  34.13710403442383,
  34.135009765625,
  34.133514404296875,
  34.13243865966797,
  34.13168716430664,
  34.131202697753906,
  34.13087844848633,
  34.13069152832031,
  34.13058090209961,
  34.13058090209961,
  34.13058853149414,
  34.13063430786133,
  34.130672454833984,
  34.13076400756836,
  34.1308708190918,
  34.13093185424805,
  34.13100814819336,
  34.13109588623047,
  34.131160736083984,
  34.13121795654297,
  34.13130569458008,
  34.1313591003418,
  34.13140106201172,
  34.1314697265625,
  34.131492614746094,
  34.13152313232422,
  34.131553649902344,
  34.13158416748047,
  34.1316032409668,
  34.13164520263672,
  34.13166046142578,
  34.131683349609375,
  34.13167953491211,
  34.13173294067383,
  34.13169479370117,
  34.131736755371094,
  34.13174057006836,
  34.13176345825195,
  34.131778717041016

In [83]:
# testM.get_weights()
testM.evaluate([1], [10], batch_size=1)
# testM.predict([2.5])
# testM.summary()

1/1 [==============================] - 0s 73ms/step - loss: 8.1723 - accuracy: 0.0000e+00


[8.17233943939209, 0.0]

array([[27.366043],
       [52.559864],
       [34.148994],
       [85.50564 ],
       [37.055973],
       [17.67611 ],
       [92.28859 ],
       [56.43584 ],
       [83.56766 ],
       [29.304028],
       [77.75369 ],
       [60.311813],
       [46.745907],
       [35.11799 ],
       [13.800136],
       [89.381615],
       [27.366043],
       [21.552082],
       [62.249798],
       [74.84672 ],
       [29.304028],
       [49.65289 ],
       [39.96295 ],
       [70.00175 ],
       [78.72269 ],
       [15.738122],
       [28.335033],
       [62.249798]], dtype=float32)

[array([[9.92701]], dtype=float32), array([1.6897041], dtype=float32)]

array([[26.507229],
       [52.31745 ],
       [33.456135],
       [86.06928 ],
       [36.43424 ],
       [16.58022 ],
       [93.01819 ],
       [56.288258],
       [84.083885],
       [28.492632],
       [78.12768 ],
       [60.259064],
       [46.361248],
       [34.448837],
       [12.609415],
       [90.040085],
       [26.507229],
       [20.551023],
       [62.24446 ],
       [75.149574],
       [28.492632],
       [49.33935 ],
       [39.412342],
       [70.18607 ],
       [79.120384],
       [14.594816],
       [27.49993 ],
       [62.24446 ]], dtype=float32)